#Using UBI as base image
FROM registry.access.redhat.com/ubi8/ubi:8.0

#Define maintainer
MAINTAINER Steven <smahalin@redhat.com>

# Labels consumed by OpenShift
LABEL io.k8s.description="A basic Apache HTTP Server with basic index.html page" \
      io.k8s.display-name="Apache HTTP Server" \
      io.openshift.expose-services="8080:http" \
      io.openshift.tags="apache, httpd"

#Install httpd(apache and disable redhat yum sub 
RUN   yum install -y --nodocs --disableplugin=subscription-manager httpd && \ 
      yum clean all --disableplugin=subscription-manager -y 

#Copy index.html to apache root
COPY ./src/ /var/www/html

# Change web server port to 8080
RUN sed -i "s/Listen 80/Listen 8080/g" /etc/httpd/conf/httpd.conf

# Permissions to allow container to run on OpenShift
RUN chgrp -R 0 /var/log/httpd /var/run/httpd && chmod -R g=u /var/log/httpd /var/run/httpd

# Change the port to 8080
EXPOSE 8080

# Run as a non-privileged user
USER 1001

# Launch httpd
CMD httpd -D FOREGROUND
